### ISSUE TITLE
Add option for threaded actions

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#1137] opened 2022-01-11 10:17 UTC
Some actions like `meeting.import` (may) take longer than the timeout of 30s, so we need the option to execute the action in a thread to circumvent this timeout.

**Comment by r-peschke** [comment] 2022-07-25 07:29
Related to https://github.com/OpenSlides/openslides-datastore-service/pull/207 and https://github.com/OpenSlides/openslides-datastore-service/issues/206 as precondition

**Comment by r-peschke** [comment] 2022-09-06 14:08
@peb-adr @jsangmeister @rrenkert :
Proposal for some Gunicorn settings (https://docs.gunicorn.org/en/stable/settings.html):
workers: Gunicorn-Doc:  2-4 x $(NUM_CORES) , others recommend 2*$(NUM_CORES) + 1
worker_class: gthread  (see https://docs.gunicorn.org/en/stable/design.html)
threads: Gunicorn-Doc:  2-4 x $(NUM_CORES)  setting only available for gthread worker class
timeout: 30 sec is okay. Backend refreshes the timeout every 10 secs (fixed in code) by worker.tmp.notify()

Fixed in Backend:
wait until notify: 10s Fixed in backend/action_worker.py gunicorn_post_worker. Period to prolongate the alive cycle of gunicorns arbiter watcher
THREAD_WATCH_TIMEOUT: 1.0sec. Time for majority of short actions to end without action_worker-notification in database
Separation of action server and presenter server, both using the same settings: we should think about having different settings

Postgres:
Min and max DATASTORE_MIN/MAX_CONNECTIONS: minimum 6 set in pg_connection_handler.py belonging to datastore-package. Explanations: IMO should be number of Gunicorn-threads + 1 for special routes to reserve_ids and to write action_worker-Notification objects per Server-process. Last ones needed to write, even if the processing of the actions occupies all db-connections for a longer time.

Extra: We should be sure that the datastore writer standard route works like a singleton, otherwise the locked-fields mechanism doesn't work as designed. The writer route to get reserved_ids could be critical, too, but as far as I know has special isolation scope. The action_worker updates aren't critical IMO.

**Comment by r-peschke** [comment] 2022-09-14 18:03
Some notes on checking by test_action_worker.py -k test_action_worker_permanent_stress. No Gunicorn in test used, but the hook is implemened in test base.py!!!
1. 4 threads started in tests
2. gunicorn timeout 30sec
3. datastore_min/max_connections: 10
4. test 4 typen a 200 Sätze in 4 request threads
5. action_worker-notifier not finished => gunicorn hook missing in test
6. 202: 10 some are in db most not: action_worker-thread finished, line 274 in action_worker.py? Move writing to request thread
7. 400: 133 all are brocken locks: try reducing locks and repeat them more times

**Comment by ostcar** [comment] 2022-09-16 05:08
What is the best way to test this in a prod environment?

Am I correct that the client can not force the backend to create an action worker. It happens automatically on long requests.

So what is a good request on a clean database?

**Comment by ostcar** [comment] 2022-09-16 15:01
I found a test action. I just create 500 users.

But I have other questions:

Why is the result in the response of the backend in a douple list? Can there be different worker from the same request? That seams strange, because with a "fast" request, you also only get one response. But even if you split in in different workers, why are there two lists? The outer is for different actions, but what is the inner list?

In the response object there is the field `fqid`. When I understand correctly,  then the collection is always `action_worker`. So you could replace `fqid` with something like `action_worker_id`

**Comment by r-peschke** [comment] 2022-09-19 15:44
> What is the best way to test this in a prod environment?
> 
> Am I correct that the client can not force the backend to create an action worker. It happens automatically on long requests.
> 
> So what is a good request on a clean database?

Do a lot in the test like importing a meeting with some data or simply use 1 action, creating or updating more instances.

**Comment by r-peschke** [comment] 2022-09-19 16:07
> I found a test action. I just create 500 users.
> 
> But I have other questions:
> 
> Why is the result in the response of the backend in a douple list? Can there be different worker from the same request? That seams strange, because with a "fast" request, you also only get one response. But even if you split in in different workers, why are there two lists? The outer is for different actions, but what is the inner list?

See https://github.com/OpenSlides/OpenSlides/wiki/Action-Service. This is the nested format to return results for all cases and with the route `handle_separately` you can split the whole payload into different (database-)transactions.
This is independent from thread watching and different workers.

> 
> In the response object there is the field `fqid`. When I understand correctly, then the collection is always `action_worker`. So you could replace `fqid` with something like `action_worker_id`

the `fqid` can be used by the recipient without knowing the collection name, hard coding it and building it, the code/result is easier to understand and the datastore can handle the fqid automatically to act on the database table with an id, when we'll get the table `models` split into real tables.

**Comment by ostcar** [comment] 2022-09-21 07:59
> See https://github.com/OpenSlides/OpenSlides/wiki/Action-Service. This is the nested format to return results for all cases and with the route `handle_separately` you can split the whole payload into different (database-)transactions. This is independent from thread watching and different workers.

I still don't get it. When I send a user.create action to create 500 users, then the response is a list with one entry that is a list with one entry with one action_worker object. Can you give me an concrete example request, where the response has more then one entry in both of the lists?

I understand why the result in `action_worker/result` is a double list. But I don't understand it for the response of the backend.

The case of a normal response of the backend and an action_worker do not have to be the same. The client has to distinguish from the http-status-code anyway.


> the `fqid` can be used by the recipient without knowing the collection name, hard coding it and building it, the code/result is easier to understand and the datastore can handle the fqid automatically to act on the database table with an id, when we'll get the table `models` split into real tables.

Please don't do this. It is very easy to add the word "action_worker/" before a number, but it is annoying to parse the string, make sure (or ignore) the part for the '/' and convert the string-number into an int.

In a lot of cases in all of our services, we have to make sure that the names of the collection to not change. If you change the collection "user" to "accout", then we also have to make a lot of changes everywhere. I don't think it is necessary to make the "action_worker" feature more flexible then all the other cases.

**Comment by r-peschke** [comment] 2022-10-06 11:26
with gunbicorn in openslides-dev-setup:
The pg_connection pool is shared betwen all processes, even presenter and action-service are using the same connection-pool

**Closed** 2022-10-26 15:10 UTC
Labels: high, feature
