### ISSUE TITLE
Meeting-admin can't invite user to his meeting

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#1459] opened 2022-09-09 16:54 UTC
Steps to reproduce:
1. Create a user with admin rights for a specific user
2. Create a user to invite him to a meeting
3. Login with user from step 1
4. Lookup for user from Step 2 by his username. The user should be presented in a single user list. Choose "auswählen" in user's line
5. The detail view of the user will be presented. Mark the group "delegierter" to make the user part of the meeting and press the "Speichern" button
6. You will see:Fehler: You are not allowed to perform action user.update. Missing permission: OrganizationManagementLevel can_manage_users in organization 1

**Comment by jsangmeister** [comment] 2022-09-12 06:17
What client version did you test this on? With the combination of https://github.com/OpenSlides/openslides-client/pull/1565 and https://github.com/OpenSlides/openslides-backend/pull/1450 this should be working now.

**Comment by r-peschke** [comment] 2022-09-12 07:16
I will test it again with current versions

**Comment by jsangmeister** [comment] 2022-10-04 08:02
Cannot reproduce on current demo. Closing this

**Closed by jsangmeister** 2022-10-04 08:02 UTC
Labels: bug, high
