### ISSUE TITLE
Can I not vote for non-temporary users?

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#512] opened 2021-03-01 08:10 UTC
I sent a request containing the following data:
```json
[
   {
      "action":"poll.create",
      "data":[
         {
            "meeting_id":1,
            "title":"Wahlgang (2)",
            "majority_method":"simple",
            "onehundred_percent_base":"valid",
            "pollmethod":"YN",
            "type":"analog",
            "options":[
               {
                  "content_object_id":"user/2",
                  "Y":"4.000000",
                  "N":"5.000000"
               },
               {
                  "content_object_id":"user/3",
                  "Y":"3.000000",
                  "N":"2.000000"
               }
            ],
            "content_object_id":"assignment/2",
            "votescast":"6.000000",
            "votesinvalid":"6.000000",
            "votesvalid":"6.000000"
         }
      ]
   }
]
```

The server sends back the following error as response:
```
Fehler: The relation content_object_id requires the following fields to be equal:
option/60/meeting_id: 1
user/2/meeting_id: None
```

Can I not vote for a non-temporary user?

**Comment by FinnStutzenstein** [comment] 2021-03-01 10:36
This is a bug. It is allowed to have non-temporary users as options as long as tey belong to the meeting.

I exepect two tests to be created: One with a non-temporary user and one with a non-temporary user with no association to the meeting. The first must succeed and the second one must fail.

**Comment by jsangmeister** [comment] 2021-03-04 08:00
Yes, this stems from this line: https://github.com/OpenSlides/OpenSlides/blob/aa05abcb0ebb529390f813362c70c67d8633c508/docs/models.yml#L1733 and is already (indirectly) adressed with #365. I haven't gotten around to implementing it yet...

**Comment by r-peschke** [comment] 2021-03-08 17:22
I propose to close this issue, because is a duplicate of [Assert equal fields for users](https://github.com/OpenSlides/openslides-backend/issues/365) assigned to [jsangmeister](https://github.com/jsangmeister).

**Comment by FinnStutzenstein** [comment] 2021-03-11 07:11
Yes, I'll close. We have to wait for #365

**Closed** 2021-03-18 08:40 UTC
Labels: backend, bug
