### ISSUE TITLE
A superadmin can do everything

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#1339] opened 2022-05-25 07:16 UTC
There are at least the actions `motion_comment.create` and `motion_comment.update` which a superadmin can't perform, if they are not assigned to the group with write permissions.
Please check, if they are another actions, which have those restrictions.

**Comment by r-peschke** [comment] 2022-05-25 08:16
> There are at least the actions `motion_comment.create` and `motion_comment.update` which a superadmin can't perform, if they are not assigned to the group with write permissions. Please check, if they are another actions, which have those restrictions.

I don't agree, see https://github.com/OpenSlides/OpenSlides/wiki/motion_comment.create.
The superadmin should be able to do everything, so he could, documented, give himself the rights to create motion_comment. But as administrative user, that is his task, he usually shouldn't be able to work without specific rights in the political/operational way.
This is an old discussion: "The housekeeper may enter in all rooms of the building, but may not assign the contracts, he'll find in some of the rooms."

**Comment by jsangmeister** [comment] 2022-08-08 08:09
closing this since working as intended

**Closed by jsangmeister** 2022-08-08 08:09 UTC
Labels: bug, needs discussion
