### ISSUE TITLE
motion.create_forwarded: include "derived_motion_ids" and "forwarding_tree_motion_ids"

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/openslides-backend#820] opened 2021-07-06 09:56 UTC
Updated [`motion.create_forwarded`](https://github.com/OpenSlides/OpenSlides/wiki/motion.create_forwarded) action description.

The original motion require to be updated as well:

- The unique id of the newly created motion has to be linked to the _origin motion_s derived_motion_ids field.
  - Deleting the newly created motion has to ensure that the corresponding entry was removed from the _origin motion_s derived_motion_ids field

- The unique id of both the newly created motion and the origin motion have to be linked in their forwarding_tree_motion_ids field
  - Deleting one of the motions should update the left forwarding_tree_motion_ids field accordingly.

**Comment by jsangmeister** [comment] 2021-07-06 14:08
> * The unique id of the newly created motion has to be linked to the _origin motion_s derived_motion_ids field.
>   
>   * Deleting the newly created motion has to ensure that the corresponding entry was removed from the _origin motion_s derived_motion_ids field

This is both done automatically by the relation handling. It should however be verified by a test, will add it to an existing one.

> * The unique id of both the newly created motion and the origin motion have to be linked in their forwarding_tree_motion_ids field
>   
>   * Deleting one of the motions should update the left forwarding_tree_motion_ids field accordingly.

Duplicate of https://github.com/OpenSlides/openslides-backend/issues/818. Closing this and transferring the second remark there.

**Closed** 2021-07-06 14:08 UTC
Labels: backend, feature
