### ISSUE TITLE
Error in organization.initial_import: Missing initial data

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#1097] opened 2021-12-10 13:16 UTC
Looks like that in production mode this action does not work because the initial-data.json has to be copied into the docker image. Can someone check this an fix the DOCKERFILE please? Thanks.

**Comment by r-peschke** [comment] 2021-12-13 17:14
It is not necessary to copy the initial-data.json into the docker image, because it is included in the backend sources. Just call the action with  `data: {}` as payload, see `https://github.com/OpenSlides/OpenSlides/wiki/organization.initial_import`

**Comment by normanjaeckel** [comment] 2021-12-13 18:58
Please have a look at the sources (https://github.com/OpenSlides/openslides-backend/blob/689eb8fd14263a15df79b2a695c0125b89b4196e/openslides_backend/shared/util.py#L85): The action runs an open() call to the device but does not find any initial-data.json because it is not part of the docker image. The backend sources are note copies completly. The directory global is not copied ...

**Comment by peb-adr** [comment] 2021-12-14 14:29
I can confirm this behavior.
https://github.com/OpenSlides/openslides-backend/pull/1103 will fix it.

**Comment by peb-adr** [comment] 2021-12-15 10:20
I just merged #1103, so closing this issue.

**Closed by peb-adr** 2021-12-15 10:20 UTC
Labels: bug, blocker
