### ISSUE TITLE
Optimise Poll stopping

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-backend#1036] opened 2021-11-20 13:40 UTC
Stopping a poll seems a bit slow. I tested it with a poll that had 100 votes. Stopping the poll took around 12 seconds

Maybe all votes are handled one by one instead as a bulk?

You can test this with the [openslides-performance](https://github.com/OpenSlides/openslides-performance) tool.

1. create a new meeting
2. create 100 users in this meeting with `openslides-performance create_users -n 100 --meeting 1`
3. create a poll in this meeting and find out the poll id  by clicking at it and look at the url in the browser.
4. Create the votes with `openslides-performance votes --poll_id 7 -n 100`

**Comment by ostcar** [comment] 2021-11-20 13:40
By the way, the poll-reset function is also very slow

**Comment by jsangmeister** [comment] 2021-11-24 13:17
closing in favor of https://github.com/OpenSlides/openslides-backend/issues/1052

**Comment by jsangmeister** [comment] 2022-03-01 16:06
Investigated this more and it seems like the problem is half datastore, half backend related: I profiled the test added in https://github.com/OpenSlides/openslides-backend/pull/1247 and of the ~45% spent during the test inside the action (the other 55% were spent preparing the data for the test), roughly 25% are spent inside the datastore, while the other 20% are spent in the backend. Of the latter, over 11% are spent inside the relation handling, where 200 get/get_many requests are created (for 100 votes). (All values are in absolute percentage points)

I analyzed the time spent in the datastore. For 1000 update events, the write request takes about 2 seconds to complete, of which 1.8 seconds are spent inside Postgres. This is because multiple queries are generated and executed for a single db event (and a single event in the write request can even generate multiple db events). https://github.com/OpenSlides/openslides-datastore-service/issues/178 already observed this behaviour. I will try and measure how much performance can be gained by reducing the amount of queries as much as possible.

The backend relation handling problem can be tackled with both of the first two approaches mentioned in #1246.

I will keep this issue updated.

**Closed** 2022-12-12 11:35 UTC
Labels: bug, performance
