### ISSUE TITLE
Implementation of the voting user delegation is missing

### ISSUE THREAD

**Issue by reiterl** [OpenSlides/openslides-backend#477] opened 2021-02-18 08:09 UTC
The implementation of user delegation needs to be done.

**Comment by jsangmeister** [comment] 2021-02-18 09:58
Duplicate of https://github.com/OpenSlides/openslides-backend/issues/445. Vote delegations are implemented, but still need to be validated.

**Closed by jsangmeister** 2021-02-18 09:58 UTC
Labels: backend
