### ISSUE TITLE
New collection user_comment

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-backend#1270] opened 2022-03-19 22:38 UTC
Currently the field `user/comment_$` is not a relation to another collection, but it contains the content of the comments directly.

This is a problem for the restricter. The restricter has currently no feature to filter template fields. If a user can see `user/comment_$`, he can also see all derivated fields like `user/comment_$42`.

 This is not a problem in all other cases. For example, if a user can see `user/group_$_ids`, he could see `user/group_$42_ids`. But he could not (automaticly) see `group/42/FIELD`. Since the content is not in the template field, it does not matter, that a user can see this template fields.

If a user A is in meeting 5, then the meeting admin of meeting 5 can see the field `user/comment_$` of the user A, not only for the meeting 5, but also for all other meetings.

When we create a separat collection (then we do in all other cases), then this problem is solved.

**Comment by jsangmeister** [comment] 2022-03-21 07:53
Don't we also have this problem for all other user template fields like `number_$` or `structure_level_$`? Then It could be better to just implement a restriction mode for template fields. Also, if I remember correctly, we also restricted the content of fields, didn't we? Meaning if `comment_$` is `["1", "2"]`, but the user has only rights for meeting 1, then the content would be restricted to `["1"]`. I assume we don't want to do the same in OS4? Because if so, this could go hand in hand.

PS: Please pay attention to https://github.com/OpenSlides/OpenSlides/wiki/Development-organization#creating-issues--pull-requests when creating new issues.

**Comment by ostcar** [comment] 2022-03-25 08:08
You are correct, that this problem exists for all template fields where the attribute `fields/type` is not `[generic-]relation[-list]`.

We did not have template fields in OS3, so there where never a restriction of template fields. Maybe you mean the restriction of `[generic-]relation-list`-Fields. For example, if the field [`committee/5/meeting_ids`](https://github.com/OpenSlides/openslides-backend/blob/af4bdfc24442c0ca67e5627b1bf348970aae3e8f/global/meta/models.yml#L617-L621) is `[1,2]`, then the restricter checks, if the user can see `meeting/1/committee_id` and `meeting/2/committee_id` (since `committee_id` is to `to`-attribute of `committee_meeting_ids`). If not, the corresponding id removed from the list. This can be done in a generic way, since all information is provided by the models.yml.

For template fields, this is not so easy.  If a user requests `user/42/comment_$5`, how should the restricter check, that the user can see it in a generic way? But we could do it with some changes to the models.yml.

There are some template fields, that have an attribute `replacement_collection`. For example `replacement_collection: meeting` But witch field of `meeting` should I check? `meeting/id` can be seen by everyone (even anonymous). So we would need to add a restriction mode to each template field in the models.yml with ha `replacement_collection`. For example:

```  
comment_$:
    type: template
    replacement_collection: meeting
    replacement_collection_mode: B
    fields: HTMLStrict
    restriction_mode: D
```

In fact `meeting` is the only 

Then there are template fields with the attribute `replacement_enum`. All of them can be replaced immediately with "normal" fields. The feature of template fields is, that the field name is unknown hat build-time and only created at runtime. But when all possible replacements are known at build-time, then we can just add this fields.

Then there are template fields, that have neither of this attributes. This are `meeting/logo_$_id` `meeting/font_$_id` (with the two back relations in the meeting collection) and `motion/amendment_paragraph_$`. I think we could also replace all of this fields with regular fields. The content can be a json-object what contains all the values. This would make the models.yml code mutch simpler in all of our services. I don't know if there is currently a case, that the client only requests one `amendment_paragraph_$23`. And even if there is a case, the performance would probably not be to poor, if all the values would be in one filed.

If we make this changes to the models.yml, then it would be possible for the restricter

**Comment by jsangmeister** [comment] 2022-04-05 06:18
I think the fields without `replacement_collection` are not relevant here, since we have no permission/restriction issue there: If you can see e.g. `meeting/logo_$_id`, you are allowed to see all replacements. Of course we could restructure them into JSON objects (I think when this was designed it was a case of "we have this template field feature so we can use it"), but I currently don't see the actual advantage of it since the current code works, so I would save the work as long as it's not needed.

Fields with `replacement_collection` are currently only present in the `user` model and only with the value `meeting`. So we could also just adjust the restriction code for this specific case without changing the model file: If these conditions hold true and the restriction mode if `D` (see https://github.com/OpenSlides/openslides-autoupdate-service/blob/5d89d070a783e0624087d1c5292fa5c229da00a5/internal/restrict/collection/user.go#L37), all meetings where Y does not have `meeting.can_manage` permission (by being in a matching group/the admin group or having OML >= `can_manage_users`) should be removed from the template field and all respective structured fields should be removed from the model.

I see that this is a rather specific condition, but I doubt that we will use the `replacement_collection` anywhere else or with another value soon, so this would be the easiest fix.

**Comment by jsangmeister** [comment] 2022-09-07 09:29
This is just a reduced version of https://github.com/OpenSlides/openslides-backend/issues/1454, right?

I will close this then.

**Closed by jsangmeister** 2022-09-07 09:29 UTC
Labels: needs discussion, feature
